var basicsByBelt = {
  'White': [
    'Horse Stance',
    'Forward Stance',
    'Cat Stance',
    'Tiger Stance',
    'Extended Forward Stance',
    'Full Twisting Punch',
    'Reverse Punch',
    'Back Knuckle Strike',
    'Back Fist Strike',
    'Bottom Fist Strike',
    'Vertical Punch',
    'Elbow Strike',
    'Elbow Smash',
    'Spear Hand Strike',
    'Spear Hand Thrust',
    'Palm Heel Strike',
    'Outward Block',
    'Inward Block',
    'Upward Block',
    'Downward Block',
    'Brush Block',
    'Upper Cross Block',
    'Lower Cross Block',
    'Bottom Fist Block',
    'Front Snap Kick',
    'Front Thrust Kick',
    'Side Snap Kick',
    'Side Thrust Kick',
    'Roundhouse Snap Kick',
    'Roundhouse Thrust Kick',
    'Back Thrust Kick',
    'Butterfly Kick',
  ],
  'Orange': [
    'Twisted Horse Stance',
    'Drop Stance',
    'Crane Stance',
    'Kempo Stance',
    'V-Hand Strike',
    'Roundhouse Punch',
    'Hook Punch',
    'Side to Side Punch',
    'Eight Knuckle Punch',
    'Shoto Chop',
    'Double Punch',
    'Peacock Block',
    'Extended Outward Block',
    'Shooting Star Block',
    'Extended Inward Block',
    'Open Hand Inward Block',
    'Extended Ridge Hand Block',
    'Open Hand Upward Block',
    'Palm Heel Block',
    'Back Snap Kick',
    'Inside Crescent Kick',
    'Outside Crescent Kick',
    'Kempo Snap Kick',
    'Hook Kick',
  ],
  'Purple': [
    'Boxer Stance',
    'Natural Stance',
    'Double Back Knuckle Strike',
    'Tiger Claw',
    'Ridge Hand Strike',
    'Peacock Strike',
    'Bear Claw',
    'Spear Hand Rake',
    'U Punch',
    'Palm Fist Block',
    'Outward Arc Block',
    'Knife Hand Block',
    'Wedge Block',
    'Scroll Block 1',
    'Scroll Block 2',
    'Scroll Block 3',
    'Side Stomp Kick',
    'Kempo Thrust Kick',
    'Heel Kick',
    'Knee Strike',
    'Football Kick',
    'Spinning Back Snap Kick',
    'Spinning Back Thrust Kicks',
    'Spinning Side Thrust Kick',
  ],
  'Blue': [
    'Glass Horse Stance',
    'Reverse Glass Horse Stance',
    'Side Drop Stance',
    'Palm Fist Strike',
    'Shoto Chop Short',
    'Shoto Chop Long',
    'Leopard\'s Paw',
    'Forearm Strike',
    'Back Fist Block',
    'Open Hand Downward Block',
    'Hook Block',
    'Ridge Hand Block',
    'Double Forearm Block',
    'Inward Axe Kick',
    'Outward Axe Kick',
    'Spinning Hook Kick',
    'Jumping Front Snap Kick',
    'Jumping Front Thrust Kick',
    'Jumping Roundhouse Snap Kick',
    'Jumping Roundhouse Thrust Kicks',
    'Spinning Roundhouse Snap Kick',
    'Spinning Roundhouse Thrust Kicks',
  ],
  'Green': [
    'Seven Star Stance',
    'Dragon Stance',
    'Wun Hop Kuen Do Drop Stance',
    'Upward Slap',
    'Rising Punch',
    'Kempo Punch',
    'Up Vertical Punch',
    'Down Vertical Punch',
    'Ear Slap',
    'Hanging Elbow Block',
    'Elbow Block',
    'Punch Block',
    'Shield Block',
    'Wheel Kick (Spinning Heel Kick)',
    'Jumping Side Snap Kick',
    'Jumping Side Thrust Kick',
    'Rising Side Thrust Kick',
    'Funny Kick',
    'Jump Spinning Crescent Kick (Inside)',
    'Drop Kick',
  ],
	'Brown': [
    'Three Point Stance',
    'Back Hand Slap',
    'One Knuckle Punch',
    'Mid-Knuckle Punch',
    'Dropping Punch',
    'Ripping Punch',
    'Thumb Up Punch',
    'One Finger Poke',
    'Whipping Hand Strike',
    'Twist-Out Punch',
    'Head Butt',
    'Upside Down Punch',
    'Upper Elbow Block',
    'Scissor Block',
    'Mantis Block',
    'Jump Spinning Back Snap Kick',
    'Jump Spinning Back Thrust Kicks',
    'Jump Spinning Roundhouse Snap Kick',
    'Jump Spinning Roundhouse Thrust Kick',
    'Tiger Tail Kick',
    'Skip Kick',
    'Back Toe Kick',
    'Sil Lum Double Front Kick',
    'Double Front Kick',
    'Scissor Kick',
    'Low Toe-Out Heel Kick',
    'Donkey Kick',
    'Jump Spinning Crescent Kick (Outside)',
    'Front Toe Hook Kick',
    'Upward Slap Kick',
    'Back Heel Kick',
  ],
  'Black': []
};

var belts = Object.keys(basicsByBelt);
